### ISSUE TITLE
Add one plate and one map per chlorophyll plate file on github for analysis

### ISSUE THREAD

**Issue by hputnam** [hputnam/Moorea_Pocillopora#5]
@chloe-gilligan the monthly files are generating duplicated data. We need just one file and one platemap per plate.

**Comment by chloe-gilligan** [comment]
@hputnam I updated the code and it does not seem to be duplicating the data anymore. The updated file is on GitHub and in the manuscript. I removed 3 outliers from June, August, and September that had high volumes and yielded high chla.ug.cm2 but can remove if needed. I also put the statistics that I got from R into the manuscript and will work on interpreting them but I pasted them in the manuscript for now. 
https://docs.google.com/document/d/1Hj5NcqDKV9WTUT9UrFTLsb0mO5jgpNJkDfOJaNap8SM/edit

**Comment by chloe-gilligan** [comment]
@hputnam Duplicate files were removed in R through coding to removed duplicate files but if needed can manually remove data
